### PR TITLE
Add an example of a 3D weighted graph using D3.js and Aframe.

### PR DESCRIPTION
**Pull request by cjroth**
Links to https://github.com/cjroth/aframe-d3-3d-graph-example

### CODE REVIEW

**Comment by ngokevin** [comment]
Actually, oops, not too awesome performance-wise.

**Comment by cjroth** [comment]
Indeed, not super performant :\

**Comment by ngokevin** [comment]
could we remove it for now until we figure out what's making it slow? we could probably speed it up, there's probably just something inefficient being done

**Comment by cjroth** [comment]
@ngokevin makes sense. I'm very new to this stuff so I don't know how to speed it up, but I will keep playing with it and see what I can come up with.

**Comment by cjroth** [comment]
@ngokevin I played with this some more on my iPhone (6) and a Vive today and it actually performed great. I think some machines are just less able to handle it than others.

**Pull request merged**
