### PR TITLE
Add german article on creating custom components

### PR DESCRIPTION
**Pull request by rubenmueller**

### CODE REVIEW

**Comment by ngokevin** [comment]
awesome article, couldn't have said it better myself.

Just heads up on some upcoming API changes in the *next release*:

- A-Frame Core has merged with A-Frame, so that people can register components with `AFRAME.registerComponents`.
- Instead of `addBehavior`, we introduced a `tick` lifecycle method.

Thanks!

**Comment by rubenmueller** [comment]
Thanks, Kevin! Also for the heads up.
Read about the changes in your WIP article – are you guys already having a rough timeframe for the next release?

**Comment by ngokevin** [comment]
at least two weeks away. I really want to get the next version out soon :)

**Comment by rubenmueller** [comment]
Awesome, looking forward to it!
Will update all my articles according to the changes. :)

**Pull request merged**
