### PR TITLE
sandbox link broken

### PR DESCRIPTION
**Pull request by dirkk0**
and corrected.
cheers, dirk

### CODE REVIEW

**Comment by Ryuno-Ki** [comment]
@dirkk0 You have merge conflicts here.

**Comment by dirkk0** [comment]
According to the log, https://proxy-controls.donmccurdy.com/ was down.
It seems to be back.
What to do now?

**Comment by Ryuno-Ki** [comment]
Usually you would [rebase on master](https://help.github.com/articles/about-git-rebase/), so you could fix the merge conflict coming up while you are doing this. Then force push your changes onto this PR.

**Comment by donmccurdy** [comment]
Thanks! 

I'm not sure about the merge conflict or the log you're referring to, but proxy-controls is still maintained.

**Comment by donmccurdy** [comment]
Oh, I see the log in Travis CI.. Looks like there are multiple unrelated links failing.. If you can fix the merge conflict we can ignore CI for now.

**Comment by dirkk0** [comment]
thanks!

**Comment by donmccurdy** [comment]
Looks like the https://ngokevin.github.io/kframe/ link got changed in resolving the conflict here

**Comment by ngokevin** [comment]
We've discontinued awesome. Thanks!

**Pull request closed without merging**
