### PR TITLE
Added aframe-react-canvas

### PR DESCRIPTION
**Pull request by maxkrieger**
For now, react only! Adds support for a 2d html5 canvas.

### CODE REVIEW

**Comment by maxkrieger** [comment]
I'm going to re-evaluate this module and see if I can componentize it later on.

**Comment by RangerMauve** [comment]
Yeah. this would be SUPER useful as a regular component. I originally thought that `react-canvas` was referring to [react-art](https://github.com/reactjs/react-art) which would warrant a hard dependency on React.

**Comment by maxkrieger** [comment]
@RangerMauve It's not really possible to use as a neatly-wrapped regular component, because you'd still want to perform canvas methods on it. What would be ideal is a hybrid module which contains a canvas object you can perform methods on, and then a way to pass that in as a material src. Problem right now is that you can't pass base64 in directly (see https://github.com/aframevr/aframe/issues/982).

**Comment by maxkrieger** [comment]
Maybe a primitive would be better? (like `<a-animation>`) Then you can perform dom methods on it like `<a-animation>` lets you run `.emit()`.

**Comment by RangerMauve** [comment]
Ideally, the component would just set up the canvas on initialization, then users could add their own components which depend on it and which would get the context to draw stuff.

**Comment by RangerMauve** [comment]
Maybe wrap over the context methods to set a flag to re-render the material on the next tick if one of them gets invoked?

**Comment by maxkrieger** [comment]
That could definitely work! Some design like:
`<a-entity canvas="myCanvas" />`

```
import {CanvasManager, Canvas} from "aframe-canvas"
aframe.registerComponent("canvas", Canvas);
CanvasManager("myCanvas").fillRect(0, 0, 20, 20);
```

**Comment by RangerMauve** [comment]
I was thinking more like this:

``` html
<a-entity canvas="width: 200; height: 200" customrect>
```

```javascript
aframe.registerComponent("canvas", Canvas);
aframe.registerComponent("customrect",{
  update: function(){
    var ctx =  this.components.canvas.get();
    ctx.fillRect(25,25,50,50);
  }
})
```

Not sure if that's the proper API to get a reference to the canvas component, though.

**Comment by maxkrieger** [comment]
Yeah cross-referencing components will be something to research. Looks like the `canvas` component is already taken for threejs rendering though :frowning: https://github.com/aframevr/aframe/blob/dev/src/components/scene/canvas.js#L3

**Comment by RangerMauve** [comment]
What about calling it "draw"?

**Comment by ngokevin** [comment]
You can cross-reference.

```js
registerComponent('whatever', {
  dependencies: ['canvas-material'],

  update: function () {
    this.components['canvas-material']
  }
});

```

**Comment by maxkrieger** [comment]
@ngokevin awesome! is there any way to reference the existing `material` component this way? Might be easier if I just called `this.components.material.updateTexture(src)`.

**Comment by ngokevin** [comment]
how about `setAttribute('material', 'src', canvasDataUri)`?

**Comment by maxkrieger** [comment]
That will work now that we got it patched, haha.

**Comment by maxkrieger** [comment]
gah.. `this.el.setAttribute()` doesn't seem to actually tick an update, even if it invokes a prop change. This is the case even for `this.el.setAttribute("material", "color", "blue");`.

**Comment by ngokevin** [comment]
Hm, is this within a React project? `setAttribute` should work within an A-Frame component to trigger scene changes.

**Comment by maxkrieger** [comment]
Nope, your component boilerplate. I'll try a codepen.

**Comment by maxkrieger** [comment]
http://codepen.io/a9/pen/OMGPwN?editors=1000 in the console, it shows that props are updated to `material: blue`.

**Comment by maxkrieger** [comment]
Manually changing the prop in the dom works, though.

**Comment by ngokevin** [comment]
Ah, common gotcha we're working on improving. Wait for the entity to load: http://codepen.io/team/mozvr/pen/eJombK?editors=1000

**Comment by ngokevin** [comment]
Fun fact, it worked in Firefox. But in Chrome, it wasn't.

**Comment by maxkrieger** [comment]
gah, you mozillans always have a way of backstabbing us chromiums :P

Thanks!

**Comment by maxkrieger** [comment]
This has gotten a little out of hand with questions but...

http://codepen.io/a9/pen/GoLJRq?editors=1000
I can't seem to get dependency/cross-referencing up. Is it just not implemented yet?

**Comment by ngokevin** [comment]
Ah, sorry. It's `this.el.components` :(

**Comment by maxkrieger** [comment]
thx :+1:

**Comment by ngokevin** [comment]
btw, we have an existing codepen for cross-component changes http://codepen.io/team/mozvr/pen/NxEpJe

**Pull request closed without merging**
