### PR TITLE
fix a ton of broken links and make formatting consistent (fixes #132)

### LINKED ISSUE #132: Fix failing Travis CI build (broken links and linting issues)
See https://travis-ci.org/aframevr/awesome-aframe/builds for list of builds.

See output from https://travis-ci.org/aframevr/awesome-aframe/jobs/218625533:

```
[503] https://www.scenevr.com
[404] https://github.com/donmccurdy/aframe-extras/tree/master/src/shadows
[404] https://ngokevin.github.io/kframe/scenes/
[403] https://shopifyvr.myshopify.com
[403] https://www.hackster.io/RONDAGDAG/control-your-earth-rover-in-virtual-reality-15a9fe
[404] https://brt-webvr-fjrtyyjbhf.now.sh/vn-geary.html
[ESOCKETTIMEDOUT] http://weatherroom.herokuapp.com
[ESOCKETTIMEDOUT] https://headshotvr.herokuapp.com
```

Seet output of https://travis-ci.org/aframevr/awesome-aframe/jobs/218625534:

```
  76:1-76:16    error    Do not use headings with similar content (55:1)      no-duplicate-headings
  300:3-300:50  error    Remove trailing slash (https://bandexplorervr.com)   trailing-slash
  305:3-305:39  error    Remove trailing slash (http://2017.ronikdesign.com)  trailing-slash
  312:3-312:42  error    Remove trailing slash (http://webvrstudio.com)       trailing-slash
  314:3-314:47  error    Remove trailing slash (https://www.ideaspacevr.org)  trailing-slash
✖ 5 errors
```

### PR DESCRIPTION
**Pull request by cvan**
also, I opened these two PRs against [`awesome-lint`](https://github.com/sindresorhus/awesome-lint):

* https://github.com/sindresorhus/awesome-lint/pull/16
* https://github.com/sindresorhus/awesome-lint/pull/17

### CODE REVIEW

**Comment by ngokevin** [comment]
R+ , feel free to push whatever to this repo. I would suggest reducing the number of extraneous links and focusing on linking to projects themselves, up to you.

**Comment by cvan** [comment]
> I would suggest reducing the number of extraneous links and focusing on linking to projects themselves, up to you.

sure thing, good idea - I'll keep that in mind going forward

**Comment by cvan** [comment]
thanks for the r+ 👍

**Pull request merged**
